
[subsection Kettle]

To build cf::noaa the build support package [package kettle] is
required, as is the accompanying application.

[para] This package must be available to the [syscmd tclsh] used to
run cf::noaa's build & installation process.

[para] The package's fossil repository can be found at
[uri http://core.tcl.tk/akupries/kettle].

[para] The relevant repository branch is [emph trunk].

[para] Kettle has a build and installation guide much like this one
for cf::noaa, which can be found at the above site and explains how to
retrieve its sources and build the package, which dependencies are
required, etc. The direct link to this guide is

[uri http://core.tcl.tk/akupries/kettle/doc/tip/embedded/www/doc/files/kettle_installer.html]

[para] Its instructions will not be repeated here. If there are
problems with their directions please file a bug against the Kettle
project, and not cf::noaa.
