/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: envelope.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "envelope.pb-c.h"
void   events__envelope__init
                     (Events__Envelope         *message)
{
  static Events__Envelope init_value = EVENTS__ENVELOPE__INIT;
  *message = init_value;
}
size_t events__envelope__get_packed_size
                     (const Events__Envelope *message)
{
  assert(message->base.descriptor == &events__envelope__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__envelope__pack
                     (const Events__Envelope *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__envelope__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__envelope__pack_to_buffer
                     (const Events__Envelope *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__envelope__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__Envelope *
       events__envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__Envelope *)
     protobuf_c_message_unpack (&events__envelope__descriptor,
                                allocator, len, data);
}
void   events__envelope__free_unpacked
                     (Events__Envelope *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__envelope__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue events__envelope__event_type__enum_values_by_number[9] =
{
  { "Heartbeat", "EVENTS__ENVELOPE__EVENT_TYPE__Heartbeat", 1 },
  { "HttpStart", "EVENTS__ENVELOPE__EVENT_TYPE__HttpStart", 2 },
  { "HttpStop", "EVENTS__ENVELOPE__EVENT_TYPE__HttpStop", 3 },
  { "HttpStartStop", "EVENTS__ENVELOPE__EVENT_TYPE__HttpStartStop", 4 },
  { "LogMessage", "EVENTS__ENVELOPE__EVENT_TYPE__LogMessage", 5 },
  { "ValueMetric", "EVENTS__ENVELOPE__EVENT_TYPE__ValueMetric", 6 },
  { "CounterEvent", "EVENTS__ENVELOPE__EVENT_TYPE__CounterEvent", 7 },
  { "Error", "EVENTS__ENVELOPE__EVENT_TYPE__Error", 8 },
  { "ContainerMetric", "EVENTS__ENVELOPE__EVENT_TYPE__ContainerMetric", 9 },
};
static const ProtobufCIntRange events__envelope__event_type__value_ranges[] = {
{1, 0},{0, 9}
};
const ProtobufCEnumValueIndex events__envelope__event_type__enum_values_by_name[9] =
{
  { "ContainerMetric", 8 },
  { "CounterEvent", 6 },
  { "Error", 7 },
  { "Heartbeat", 0 },
  { "HttpStart", 1 },
  { "HttpStartStop", 3 },
  { "HttpStop", 2 },
  { "LogMessage", 4 },
  { "ValueMetric", 5 },
};
const ProtobufCEnumDescriptor events__envelope__event_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "events.Envelope.EventType",
  "EventType",
  "Events__Envelope__EventType",
  "events",
  9,
  events__envelope__event_type__enum_values_by_number,
  9,
  events__envelope__event_type__enum_values_by_name,
  1,
  events__envelope__event_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor events__envelope__field_descriptors[12] =
{
  {
    "origin",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, origin),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eventType",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, eventtype),
    &events__envelope__event_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heartbeat",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, heartbeat),
    &events__heartbeat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "httpStart",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, httpstart),
    &events__http_start__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "httpStop",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, httpstop),
    &events__http_stop__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Events__Envelope, has_timestamp),
    offsetof(Events__Envelope, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "httpStartStop",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, httpstartstop),
    &events__http_start_stop__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logMessage",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, logmessage),
    &events__log_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "valueMetric",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, valuemetric),
    &events__value_metric__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counterEvent",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, counterevent),
    &events__counter_event__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, error),
    &events__error__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "containerMetric",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Envelope, containermetric),
    &events__container_metric__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__envelope__field_indices_by_name[] = {
  11,   /* field[11] = containerMetric */
  9,   /* field[9] = counterEvent */
  10,   /* field[10] = error */
  1,   /* field[1] = eventType */
  2,   /* field[2] = heartbeat */
  3,   /* field[3] = httpStart */
  6,   /* field[6] = httpStartStop */
  4,   /* field[4] = httpStop */
  7,   /* field[7] = logMessage */
  0,   /* field[0] = origin */
  5,   /* field[5] = timestamp */
  8,   /* field[8] = valueMetric */
};
static const ProtobufCIntRange events__envelope__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor events__envelope__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.Envelope",
  "Envelope",
  "Events__Envelope",
  "events",
  sizeof(Events__Envelope),
  12,
  events__envelope__field_descriptors,
  events__envelope__field_indices_by_name,
  1,  events__envelope__number_ranges,
  (ProtobufCMessageInit) events__envelope__init,
  NULL,NULL,NULL    /* reserved[123] */
};
