/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: error.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "error.pb-c.h"
void   events__error__init
                     (Events__Error         *message)
{
  static Events__Error init_value = EVENTS__ERROR__INIT;
  *message = init_value;
}
size_t events__error__get_packed_size
                     (const Events__Error *message)
{
  assert(message->base.descriptor == &events__error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__error__pack
                     (const Events__Error *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__error__pack_to_buffer
                     (const Events__Error *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__Error *
       events__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__Error *)
     protobuf_c_message_unpack (&events__error__descriptor,
                                allocator, len, data);
}
void   events__error__free_unpacked
                     (Events__Error *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor events__error__field_descriptors[3] =
{
  {
    "source",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__Error, source),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Events__Error, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__Error, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__error__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = message */
  0,   /* field[0] = source */
};
static const ProtobufCIntRange events__error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor events__error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.Error",
  "Error",
  "Events__Error",
  "events",
  sizeof(Events__Error),
  3,
  events__error__field_descriptors,
  events__error__field_indices_by_name,
  1,  events__error__number_ranges,
  (ProtobufCMessageInit) events__error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
