/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: heartbeat.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "heartbeat.pb-c.h"
void   events__heartbeat__init
                     (Events__Heartbeat         *message)
{
  static Events__Heartbeat init_value = EVENTS__HEARTBEAT__INIT;
  *message = init_value;
}
size_t events__heartbeat__get_packed_size
                     (const Events__Heartbeat *message)
{
  assert(message->base.descriptor == &events__heartbeat__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__heartbeat__pack
                     (const Events__Heartbeat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__heartbeat__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__heartbeat__pack_to_buffer
                     (const Events__Heartbeat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__heartbeat__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__Heartbeat *
       events__heartbeat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__Heartbeat *)
     protobuf_c_message_unpack (&events__heartbeat__descriptor,
                                allocator, len, data);
}
void   events__heartbeat__free_unpacked
                     (Events__Heartbeat *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__heartbeat__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor events__heartbeat__field_descriptors[4] =
{
  {
    "sentCount",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Events__Heartbeat, sentcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receivedCount",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Events__Heartbeat, receivedcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorCount",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Events__Heartbeat, errorcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "controlMessageIdentifier",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__Heartbeat, controlmessageidentifier),
    &events__uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__heartbeat__field_indices_by_name[] = {
  3,   /* field[3] = controlMessageIdentifier */
  2,   /* field[2] = errorCount */
  1,   /* field[1] = receivedCount */
  0,   /* field[0] = sentCount */
};
static const ProtobufCIntRange events__heartbeat__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor events__heartbeat__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.Heartbeat",
  "Heartbeat",
  "Events__Heartbeat",
  "events",
  sizeof(Events__Heartbeat),
  4,
  events__heartbeat__field_descriptors,
  events__heartbeat__field_indices_by_name,
  1,  events__heartbeat__number_ranges,
  (ProtobufCMessageInit) events__heartbeat__init,
  NULL,NULL,NULL    /* reserved[123] */
};
