/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: http.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "http.pb-c.h"
void   events__http_start__init
                     (Events__HttpStart         *message)
{
  static Events__HttpStart init_value = EVENTS__HTTP_START__INIT;
  *message = init_value;
}
size_t events__http_start__get_packed_size
                     (const Events__HttpStart *message)
{
  assert(message->base.descriptor == &events__http_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__http_start__pack
                     (const Events__HttpStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__http_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__http_start__pack_to_buffer
                     (const Events__HttpStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__http_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__HttpStart *
       events__http_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__HttpStart *)
     protobuf_c_message_unpack (&events__http_start__descriptor,
                                allocator, len, data);
}
void   events__http_start__free_unpacked
                     (Events__HttpStart *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__http_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   events__http_stop__init
                     (Events__HttpStop         *message)
{
  static Events__HttpStop init_value = EVENTS__HTTP_STOP__INIT;
  *message = init_value;
}
size_t events__http_stop__get_packed_size
                     (const Events__HttpStop *message)
{
  assert(message->base.descriptor == &events__http_stop__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__http_stop__pack
                     (const Events__HttpStop *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__http_stop__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__http_stop__pack_to_buffer
                     (const Events__HttpStop *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__http_stop__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__HttpStop *
       events__http_stop__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__HttpStop *)
     protobuf_c_message_unpack (&events__http_stop__descriptor,
                                allocator, len, data);
}
void   events__http_stop__free_unpacked
                     (Events__HttpStop *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__http_stop__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   events__http_start_stop__init
                     (Events__HttpStartStop         *message)
{
  static Events__HttpStartStop init_value = EVENTS__HTTP_START_STOP__INIT;
  *message = init_value;
}
size_t events__http_start_stop__get_packed_size
                     (const Events__HttpStartStop *message)
{
  assert(message->base.descriptor == &events__http_start_stop__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__http_start_stop__pack
                     (const Events__HttpStartStop *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__http_start_stop__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__http_start_stop__pack_to_buffer
                     (const Events__HttpStartStop *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__http_start_stop__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__HttpStartStop *
       events__http_start_stop__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__HttpStartStop *)
     protobuf_c_message_unpack (&events__http_start_stop__descriptor,
                                allocator, len, data);
}
void   events__http_start_stop__free_unpacked
                     (Events__HttpStartStop *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__http_start_stop__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor events__http_start__field_descriptors[11] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, requestid),
    &events__uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peerType",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, peertype),
    &events__peer_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, method),
    &events__method__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uri",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, uri),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remoteAddress",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, remoteaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "userAgent",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, useragent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parentRequestId",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, parentrequestid),
    &events__uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "applicationId",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, applicationid),
    &events__uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instanceIndex",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Events__HttpStart, has_instanceindex),
    offsetof(Events__HttpStart, instanceindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instanceId",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStart, instanceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__http_start__field_indices_by_name[] = {
  8,   /* field[8] = applicationId */
  10,   /* field[10] = instanceId */
  9,   /* field[9] = instanceIndex */
  3,   /* field[3] = method */
  7,   /* field[7] = parentRequestId */
  2,   /* field[2] = peerType */
  5,   /* field[5] = remoteAddress */
  1,   /* field[1] = requestId */
  0,   /* field[0] = timestamp */
  4,   /* field[4] = uri */
  6,   /* field[6] = userAgent */
};
static const ProtobufCIntRange events__http_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor events__http_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.HttpStart",
  "HttpStart",
  "Events__HttpStart",
  "events",
  sizeof(Events__HttpStart),
  11,
  events__http_start__field_descriptors,
  events__http_start__field_indices_by_name,
  1,  events__http_start__number_ranges,
  (ProtobufCMessageInit) events__http_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor events__http_stop__field_descriptors[7] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStop, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uri",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStop, uri),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestId",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStop, requestid),
    &events__uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peerType",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStop, peertype),
    &events__peer_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statusCode",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStop, statuscode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contentLength",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStop, contentlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "applicationId",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStop, applicationid),
    &events__uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__http_stop__field_indices_by_name[] = {
  6,   /* field[6] = applicationId */
  5,   /* field[5] = contentLength */
  3,   /* field[3] = peerType */
  2,   /* field[2] = requestId */
  4,   /* field[4] = statusCode */
  0,   /* field[0] = timestamp */
  1,   /* field[1] = uri */
};
static const ProtobufCIntRange events__http_stop__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor events__http_stop__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.HttpStop",
  "HttpStop",
  "Events__HttpStop",
  "events",
  sizeof(Events__HttpStop),
  7,
  events__http_stop__field_descriptors,
  events__http_stop__field_indices_by_name,
  1,  events__http_stop__number_ranges,
  (ProtobufCMessageInit) events__http_stop__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor events__http_start_stop__field_descriptors[14] =
{
  {
    "startTimestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, starttimestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stopTimestamp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, stoptimestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "requestId",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, requestid),
    &events__uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peerType",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, peertype),
    &events__peer_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, method),
    &events__method__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uri",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, uri),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "remoteAddress",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, remoteaddress),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "userAgent",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, useragent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statusCode",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, statuscode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contentLength",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, contentlength),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parentRequestId",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, parentrequestid),
    &events__uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "applicationId",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, applicationid),
    &events__uuid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instanceIndex",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Events__HttpStartStop, has_instanceindex),
    offsetof(Events__HttpStartStop, instanceindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instanceId",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__HttpStartStop, instanceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__http_start_stop__field_indices_by_name[] = {
  11,   /* field[11] = applicationId */
  9,   /* field[9] = contentLength */
  13,   /* field[13] = instanceId */
  12,   /* field[12] = instanceIndex */
  4,   /* field[4] = method */
  10,   /* field[10] = parentRequestId */
  3,   /* field[3] = peerType */
  6,   /* field[6] = remoteAddress */
  2,   /* field[2] = requestId */
  0,   /* field[0] = startTimestamp */
  8,   /* field[8] = statusCode */
  1,   /* field[1] = stopTimestamp */
  5,   /* field[5] = uri */
  7,   /* field[7] = userAgent */
};
static const ProtobufCIntRange events__http_start_stop__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor events__http_start_stop__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.HttpStartStop",
  "HttpStartStop",
  "Events__HttpStartStop",
  "events",
  sizeof(Events__HttpStartStop),
  14,
  events__http_start_stop__field_descriptors,
  events__http_start_stop__field_indices_by_name,
  1,  events__http_start_stop__number_ranges,
  (ProtobufCMessageInit) events__http_start_stop__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue events__peer_type__enum_values_by_number[2] =
{
  { "Client", "EVENTS__PEER_TYPE__Client", 1 },
  { "Server", "EVENTS__PEER_TYPE__Server", 2 },
};
static const ProtobufCIntRange events__peer_type__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex events__peer_type__enum_values_by_name[2] =
{
  { "Client", 0 },
  { "Server", 1 },
};
const ProtobufCEnumDescriptor events__peer_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "events.PeerType",
  "PeerType",
  "Events__PeerType",
  "events",
  2,
  events__peer_type__enum_values_by_number,
  2,
  events__peer_type__enum_values_by_name,
  1,
  events__peer_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue events__method__enum_values_by_number[5] =
{
  { "GET", "EVENTS__METHOD__GET", 1 },
  { "POST", "EVENTS__METHOD__POST", 2 },
  { "PUT", "EVENTS__METHOD__PUT", 3 },
  { "DELETE", "EVENTS__METHOD__DELETE", 4 },
  { "HEAD", "EVENTS__METHOD__HEAD", 5 },
};
static const ProtobufCIntRange events__method__value_ranges[] = {
{1, 0},{0, 5}
};
const ProtobufCEnumValueIndex events__method__enum_values_by_name[5] =
{
  { "DELETE", 3 },
  { "GET", 0 },
  { "HEAD", 4 },
  { "POST", 1 },
  { "PUT", 2 },
};
const ProtobufCEnumDescriptor events__method__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "events.Method",
  "Method",
  "Events__Method",
  "events",
  5,
  events__method__enum_values_by_number,
  5,
  events__method__enum_values_by_name,
  1,
  events__method__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
