/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: log.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "log.pb-c.h"
void   events__log_message__init
                     (Events__LogMessage         *message)
{
  static Events__LogMessage init_value = EVENTS__LOG_MESSAGE__INIT;
  *message = init_value;
}
size_t events__log_message__get_packed_size
                     (const Events__LogMessage *message)
{
  assert(message->base.descriptor == &events__log_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__log_message__pack
                     (const Events__LogMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__log_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__log_message__pack_to_buffer
                     (const Events__LogMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__log_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__LogMessage *
       events__log_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__LogMessage *)
     protobuf_c_message_unpack (&events__log_message__descriptor,
                                allocator, len, data);
}
void   events__log_message__free_unpacked
                     (Events__LogMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__log_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue events__log_message__message_type__enum_values_by_number[2] =
{
  { "OUT", "EVENTS__LOG_MESSAGE__MESSAGE_TYPE__OUT", 1 },
  { "ERR", "EVENTS__LOG_MESSAGE__MESSAGE_TYPE__ERR", 2 },
};
static const ProtobufCIntRange events__log_message__message_type__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex events__log_message__message_type__enum_values_by_name[2] =
{
  { "ERR", 1 },
  { "OUT", 0 },
};
const ProtobufCEnumDescriptor events__log_message__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "events.LogMessage.MessageType",
  "MessageType",
  "Events__LogMessage__MessageType",
  "events",
  2,
  events__log_message__message_type__enum_values_by_number,
  2,
  events__log_message__message_type__enum_values_by_name,
  1,
  events__log_message__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor events__log_message__field_descriptors[6] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Events__LogMessage, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Events__LogMessage, message_type),
    &events__log_message__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Events__LogMessage, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__LogMessage, app_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_type",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__LogMessage, source_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_instance",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__LogMessage, source_instance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__log_message__field_indices_by_name[] = {
  3,   /* field[3] = app_id */
  0,   /* field[0] = message */
  1,   /* field[1] = message_type */
  5,   /* field[5] = source_instance */
  4,   /* field[4] = source_type */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange events__log_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor events__log_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.LogMessage",
  "LogMessage",
  "Events__LogMessage",
  "events",
  sizeof(Events__LogMessage),
  6,
  events__log_message__field_descriptors,
  events__log_message__field_indices_by_name,
  1,  events__log_message__number_ranges,
  (ProtobufCMessageInit) events__log_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
