/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: metric.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "metric.pb-c.h"
void   events__value_metric__init
                     (Events__ValueMetric         *message)
{
  static Events__ValueMetric init_value = EVENTS__VALUE_METRIC__INIT;
  *message = init_value;
}
size_t events__value_metric__get_packed_size
                     (const Events__ValueMetric *message)
{
  assert(message->base.descriptor == &events__value_metric__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__value_metric__pack
                     (const Events__ValueMetric *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__value_metric__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__value_metric__pack_to_buffer
                     (const Events__ValueMetric *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__value_metric__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__ValueMetric *
       events__value_metric__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__ValueMetric *)
     protobuf_c_message_unpack (&events__value_metric__descriptor,
                                allocator, len, data);
}
void   events__value_metric__free_unpacked
                     (Events__ValueMetric *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__value_metric__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   events__counter_event__init
                     (Events__CounterEvent         *message)
{
  static Events__CounterEvent init_value = EVENTS__COUNTER_EVENT__INIT;
  *message = init_value;
}
size_t events__counter_event__get_packed_size
                     (const Events__CounterEvent *message)
{
  assert(message->base.descriptor == &events__counter_event__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__counter_event__pack
                     (const Events__CounterEvent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__counter_event__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__counter_event__pack_to_buffer
                     (const Events__CounterEvent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__counter_event__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__CounterEvent *
       events__counter_event__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__CounterEvent *)
     protobuf_c_message_unpack (&events__counter_event__descriptor,
                                allocator, len, data);
}
void   events__counter_event__free_unpacked
                     (Events__CounterEvent *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__counter_event__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   events__container_metric__init
                     (Events__ContainerMetric         *message)
{
  static Events__ContainerMetric init_value = EVENTS__CONTAINER_METRIC__INIT;
  *message = init_value;
}
size_t events__container_metric__get_packed_size
                     (const Events__ContainerMetric *message)
{
  assert(message->base.descriptor == &events__container_metric__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events__container_metric__pack
                     (const Events__ContainerMetric *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events__container_metric__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events__container_metric__pack_to_buffer
                     (const Events__ContainerMetric *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events__container_metric__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Events__ContainerMetric *
       events__container_metric__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Events__ContainerMetric *)
     protobuf_c_message_unpack (&events__container_metric__descriptor,
                                allocator, len, data);
}
void   events__container_metric__free_unpacked
                     (Events__ContainerMetric *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &events__container_metric__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor events__value_metric__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__ValueMetric, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Events__ValueMetric, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unit",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__ValueMetric, unit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__value_metric__field_indices_by_name[] = {
  0,   /* field[0] = name */
  2,   /* field[2] = unit */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange events__value_metric__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor events__value_metric__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.ValueMetric",
  "ValueMetric",
  "Events__ValueMetric",
  "events",
  sizeof(Events__ValueMetric),
  3,
  events__value_metric__field_descriptors,
  events__value_metric__field_indices_by_name,
  1,  events__value_metric__number_ranges,
  (ProtobufCMessageInit) events__value_metric__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor events__counter_event__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__CounterEvent, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delta",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Events__CounterEvent, delta),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Events__CounterEvent, has_total),
    offsetof(Events__CounterEvent, total),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__counter_event__field_indices_by_name[] = {
  1,   /* field[1] = delta */
  0,   /* field[0] = name */
  2,   /* field[2] = total */
};
static const ProtobufCIntRange events__counter_event__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor events__counter_event__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.CounterEvent",
  "CounterEvent",
  "Events__CounterEvent",
  "events",
  sizeof(Events__CounterEvent),
  3,
  events__counter_event__field_descriptors,
  events__counter_event__field_indices_by_name,
  1,  events__counter_event__number_ranges,
  (ProtobufCMessageInit) events__counter_event__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor events__container_metric__field_descriptors[5] =
{
  {
    "applicationId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Events__ContainerMetric, applicationid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instanceIndex",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Events__ContainerMetric, instanceindex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpuPercentage",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Events__ContainerMetric, cpupercentage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memoryBytes",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Events__ContainerMetric, memorybytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "diskBytes",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Events__ContainerMetric, diskbytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events__container_metric__field_indices_by_name[] = {
  0,   /* field[0] = applicationId */
  2,   /* field[2] = cpuPercentage */
  4,   /* field[4] = diskBytes */
  1,   /* field[1] = instanceIndex */
  3,   /* field[3] = memoryBytes */
};
static const ProtobufCIntRange events__container_metric__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor events__container_metric__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "events.ContainerMetric",
  "ContainerMetric",
  "Events__ContainerMetric",
  "events",
  sizeof(Events__ContainerMetric),
  5,
  events__container_metric__field_descriptors,
  events__container_metric__field_indices_by_name,
  1,  events__container_metric__number_ranges,
  (ProtobufCMessageInit) events__container_metric__init,
  NULL,NULL,NULL    /* reserved[123] */
};
