/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: uuid.proto */

#ifndef PROTOBUF_C_uuid_2eproto__INCLUDED
#define PROTOBUF_C_uuid_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Events__UUID Events__UUID;


/* --- enums --- */


/* --- messages --- */

/*
 * / Type representing a 128-bit UUID.
 */
struct  _Events__UUID
{
  ProtobufCMessage base;
  uint64_t low;
  uint64_t high;
};
#define EVENTS__UUID__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&events__uuid__descriptor) \
    , 0, 0 }


/* Events__UUID methods */
void   events__uuid__init
                     (Events__UUID         *message);
size_t events__uuid__get_packed_size
                     (const Events__UUID   *message);
size_t events__uuid__pack
                     (const Events__UUID   *message,
                      uint8_t             *out);
size_t events__uuid__pack_to_buffer
                     (const Events__UUID   *message,
                      ProtobufCBuffer     *buffer);
Events__UUID *
       events__uuid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   events__uuid__free_unpacked
                     (Events__UUID *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Events__UUID_Closure)
                 (const Events__UUID *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor events__uuid__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_uuid_2eproto__INCLUDED */
